GlobalParameters:
  NumElementsToValidate: -1
  KernelTime: True
  NewClient: 2
  # DataInitTypeA: 1
  # DataInitTypeB: 1
  # DataInitTypeAlpha: 1
  # DataInitTypeBeta: 0
  # PrintTensorA: 1
  # PrintTensorB: 1
  # PrintTensorC: 1
  PrintSolutionRejectionReason: True
  ValidationMaxToPrint: 4
  NumBenchmarks: 16
BenchmarkProblems:

  ########################################
  # NN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: c
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - PrefetchGlobalRead: [True]
      ForkParameters:
        - PrefetchLocalRead: [True]
        - WorkGroupMapping: [1]
        - VectorWidth: [2]
        - MatrixInstruction:
          - [ 4, 4, 1, 16]
          - [16, 16, 1, 4]
          - [16, 16, 4, 1]
          - [32, 32, 1, 2] # *
          - [32, 32, 2, 1]
        - ThreadTile:
          - [ 1, 32 ] # *
          - [ 2, 32 ]
          - [ 2, 64 ]
        - WorkGroup:
          - [ 64, 4, 1 ] # *
          - [ 32, 8, 1 ]
        - DepthU: [ 8 ]
        - AssertFree0ElementMultiple: [1]
        - AssertFree1ElementMultiple: [1]
        - InnerUnroll: [1,2]
        # - SuppressNoLoadLoop: [1]
        # - ScheduleIterAlg: [1,3]
        # - GlobalReadVectorWidth: [1,2]
        # - WaveSeparateGlobalReadA: [1]
        # - WaveSeparateGlobalReadB: [1]
        # - TransposeLDS: [1]
        # - LdsPadA: [1,2]
        # - LdsPadB: [1,2]
        # - StoreRemapVectorWidth: [1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [128], [1], [256] ] # *
          - Range: [ [63], [128], [1], [256] ] # edge m
          - Range: [ [64], [127], [1], [256] ] # edge n
          # - Range: [ [63,3,72], [125,3,131], [1], [256] ]
          - Range: [ [960], [1024], [1], [1024] ]
          - Range: [ [959], [1023], [1], [1024] ]